name: build and deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  
env:
  artifacts_dir: src/StupidComments/bin/Release/net6.0/publish/wwwroot
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish --no-restore -c Release
    - name: Change base-tag in index.html from / to StupidComments
      run: sed -i 's/<base href="\/" \/>/<base href="\/StupidComments\/" \/>/g' $artifacts_dir/index.html
    - name: Add .nojekyll file
      run: touch $artifacts_dir/.nojekyll
    - name: copy index.html to 404.html
      run: cp $artifacts_dir/index.html $artifacts_dir/404.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ${{ env.artifacts_dir }}
